title: Creative Coding (DM-GY 6063) Fall 2023 Section D

baseurl: ""
include: ["_pages"]

# Build settings
markdown: kramdown

# Local dev settings
port: 8114

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      permalink: :basename/
  - scope:
      path: "README.md"
    values:
      layout: "page"
      permalink: /
      title: DM-GY 6063 2023F D Syllabus